### PR TITLE
hw03+hw04

### PR DESCRIPTION
**Pull request by kjkrVdxB**

### CODE REVIEW

**Comment by dboulytchev** [comment]
Missing file?

**Comment by dboulytchev** [comment]
db@coolest:~/tmp/LRP-2021/UNI$ ghc -c Term.hs 

Term.hs:12:1: error:
    Failed to load interface for ‘Util’
    It is a member of the hidden package ‘ghc-8.0.2’.
    Use -v to see a list of the files searched for.

**Comment by kjkrVdxB** [comment]
No, Util is in the root of the project, so you should run ghc from there, like so:
`db@coolest:~/tmp/LRP-2021$ ghc -c UNI/Term.hs`
This is because it's used both by UNI and by SAT.
UPD: see comment below, this should not be needed anymore.

**Comment by kjkrVdxB** [comment]
Copied Util.hs to UNI and SAT so it's easier to run the tests.

**Pull request closed without merging**
